// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdlknpwplrbyreonhneq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbGtucHdwbHJieXJlb25obmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTA3MzYsImV4cCI6MjA2MDQ4NjczNn0.3GkjEjndb2g9e3GYbVqpPGZnkUSQKUivgHEMkBR49oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);